//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ch.deceed.deployNET.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ch.deceed.deployNET.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to {0} application pool &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorAppPool {
            get {
                return ResourceManager.GetString("ErrorAppPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to build project &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorBuild {
            get {
                return ResourceManager.GetString("ErrorBuild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file or directory &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorCopy {
            get {
                return ResourceManager.GetString("ErrorCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to copy file or directory &quot;{0}&quot; because it does no exist..
        /// </summary>
        internal static string ErrorCopyNotFound {
            get {
                return ResourceManager.GetString("ErrorCopyNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete file &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorDeleteFile {
            get {
                return ResourceManager.GetString("ErrorDeleteFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to delete folder &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorDeleteFolder {
            get {
                return ResourceManager.GetString("ErrorDeleteFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to execute process &quot;{0}&quot; with arguments &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorExecute {
            get {
                return ResourceManager.GetString("ErrorExecute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to complete FTP command..
        /// </summary>
        internal static string ErrorFtp {
            get {
                return ResourceManager.GetString("ErrorFtp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download file &quot;{0}&quot; via FTP..
        /// </summary>
        internal static string ErrorFtpDownload {
            get {
                return ResourceManager.GetString("ErrorFtpDownload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload file &quot;{0}&quot; via FTP..
        /// </summary>
        internal static string ErrorFtpUpload {
            get {
                return ResourceManager.GetString("ErrorFtpUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to upload file &quot;{0}&quot; via FTP because it does not exist..
        /// </summary>
        internal static string ErrorFtpUploadNotFound {
            get {
                return ResourceManager.GetString("ErrorFtpUploadNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to download file &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorHttp {
            get {
                return ResourceManager.GetString("ErrorHttp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move file or directory &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorMove {
            get {
                return ResourceManager.GetString("ErrorMove", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to move file or directory &quot;{0}&quot; because it does not exist..
        /// </summary>
        internal static string ErrorMoveNotFound {
            get {
                return ResourceManager.GetString("ErrorMoveNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application pool &quot;{0}&quot; not found..
        /// </summary>
        internal static string ErrorNoAppPool {
            get {
                return ResourceManager.GetString("ErrorNoAppPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename file &quot;{0}&quot; to &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorRename {
            get {
                return ResourceManager.GetString("ErrorRename", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to rename file &quot;{0}&quot; because it does not exist..
        /// </summary>
        internal static string ErrorRenameNotFound {
            get {
                return ResourceManager.GetString("ErrorRenameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to replace text in file &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorReplace {
            get {
                return ResourceManager.GetString("ErrorReplace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to replace text in file &quot;{0}&quot; because it does not exist..
        /// </summary>
        internal static string ErrorReplaceNotFound {
            get {
                return ResourceManager.GetString("ErrorReplaceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to {0} service &quot;{1}&quot;..
        /// </summary>
        internal static string ErrorService {
            get {
                return ResourceManager.GetString("ErrorService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to start application pool..
        /// </summary>
        internal static string ErrorStartAppPool {
            get {
                return ResourceManager.GetString("ErrorStartAppPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to stop application pool..
        /// </summary>
        internal static string ErrorStopAppPool {
            get {
                return ResourceManager.GetString("ErrorStopAppPool", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract file &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorUnZip {
            get {
                return ResourceManager.GetString("ErrorUnZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract file &quot;{0}&quot; because it is invalid..
        /// </summary>
        internal static string ErrorUnZipInvalid {
            get {
                return ResourceManager.GetString("ErrorUnZipInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to extract file &quot;{0}&quot; because it does not exist..
        /// </summary>
        internal static string ErrorUnZipSrcNotFound {
            get {
                return ResourceManager.GetString("ErrorUnZipSrcNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to zip directory &quot;{0}&quot;..
        /// </summary>
        internal static string ErrorZip {
            get {
                return ResourceManager.GetString("ErrorZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failed to zip directory &quot;{0}&quot; because it does not exist..
        /// </summary>
        internal static string ErrorZipSrcNotFound {
            get {
                return ResourceManager.GetString("ErrorZipSrcNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap helpicon {
            get {
                object obj = ResourceManager.GetObject("helpicon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
